BUILTINS_DICTIONARY_SOURCE = (
    "import builtins\n"
    "broad_exception = builtins.__dict__[\"Exception\"]\n"
    "is_instance = builtins.__dict__[\"isinstance\"]\n"
    "static = builtins.__dict__[\"staticmethod\"]\n"
    "\n"
    "def read_value() -> None:\n"
    "    try:\n"
    "        raise ValueError\n"
    "    except broad_exception:\n"
    "        return\n"
    "\n"
    "def check_value(value: str) -> bool:\n"
    "    return is_instance(value, str)\n"
    "\n"
    "class Factory:\n"
    "    @static\n"
    "    def build() -> int:\n"
    "        return 1\n"
)
